# -*- coding: utf-8 -*-
"""test_script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYYaCVM6hJGZDZ5MOtfpi-nJyOvGts7D
"""

"""
Question 4: GenAI Clinical Data Assistant - Test Script
Runs 3 example queries and prints results

Author: Adashi Odama

This script demonstrates the ClinicalTrialDataAgent in action.
It loads the ADAE dataset, initializes the agent, and runs three
clinically relevant queries to showcase the Agent'a abilities
"""

import pandas as pd
import json

#------------------------------------------------------------------------------
# Load ADAE Dataset
#------------------------------------------------------------------------------


file_path = "/content/adae.csv"

adae = pd.read_csv(file_path)

print(f"✓ Loaded from: {file_path}")


#------------------------------------------------------------------------------
# Define Schema
#------------------------------------------------------------------------------

ADAE_SCHEMA = {
    "USUBJID": {
        "description": "Unique Subject Identifier",
        "type": "identifier",
        "keywords": ["subject", "patient", "participant", "ID", "identifier"]
    },
    "AETERM": {
        "description": "Reported Term for the Adverse Event",
        "type": "categorical",
        "keywords": ["condition", "event", "symptom", "pruritus", "headache", "nausea", "dizziness", "itching"]
    },
    "AESEV": {
        "description": "Severity/Intensity of Adverse Event",
        "type": "categorical",
        "valid_values": ["MILD", "MODERATE", "SEVERE"],
        "keywords": ["severity", "intensity", "mild", "moderate", "severe"]
    },
    "AESOC": {
        "description": "Primary System Organ Class",
        "type": "categorical",
        "keywords": ["body system", "organ class", "cardiac", "nervous", "skin", "gastrointestinal"]
    },
    "SAFFL": {
        "description": "Safety Population Flag",
        "type": "flag",
        "keywords": ["safety population", "safety flag"]
    },
    "TRTEMFL": {
        "description": "Treatment Emergent Analysis Flag",
        "type": "flag",
        "keywords": ["treatment emergent", "treatment-emergent", "emergent", "teae"]
    }
}

#------------------------------------------------------------------------------
# ClinicalTrialDataAgent Class
#------------------------------------------------------------------------------

class ClinicalTrialDataAgent:
    """Mock LLM agent that parses natural language questions into structured queries."""

    def __init__(self, schema):
        self.schema = schema

    def parse_question(self, question):
        """Parse NL question into structured JSON output."""
        question_lower = question.lower()

        result = {
            "target_column": None,
            "filter_value": None,
                  }

        # Check for severity
        if any(word in question_lower for word in ['mild', 'moderate', 'severe', 'severity', 'intensity']):
            result['target_column'] = 'AESEV'
            if 'mild' in question_lower:
                result['filter_value'] = 'MILD'
            elif 'moderate' in question_lower:
                result['filter_value'] = 'MODERATE'
            elif 'severe' in question_lower:
                result['filter_value'] = 'SEVERE'
            return result

        # Check for treatment-emergent
        if any(phrase in question_lower for phrase in ['treatment emergent', 'treatment-emergent', 'teae', 'emergent']):
            result['target_column'] = 'TRTEMFL'
            result['filter_value'] = 'Y'
            return result

        # Check for safety population
        if 'safety population' in question_lower or 'safety flag' in question_lower:
            result['target_column'] = 'SAFFL'
            result['filter_value'] = 'Y'
            return result

        # Check for System Organ Class
        soc_mappings = {
            'cardiac': 'CARDIAC DISORDERS',
            'heart': 'CARDIAC DISORDERS',
            'nervous': 'NERVOUS SYSTEM DISORDERS',
            'brain': 'NERVOUS SYSTEM DISORDERS',
            'skin': 'SKIN AND SUBCUTANEOUS TISSUE DISORDERS',
            'gastrointestinal': 'GASTROINTESTINAL DISORDERS',
            'respiratory': 'RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS'
                      }

        for keyword, soc_value in soc_mappings.items():
            if keyword in question_lower:
                result['target_column'] = 'AESOC'
                result['filter_value'] = soc_value
                return result

        # Check for specific AE terms
        term_mappings = {
            'headache': 'HEADACHE',
            'nausea': 'NAUSEA',
            'dizziness': 'DIZZINESS',
            'pruritus': 'PRURITUS',
            'itching': 'PRURITUS',
            'rash': 'RASH',
            'diarrhoea': 'DIARRHOEA',
            'diarrhea': 'DIARRHOEA'
                        }

        for keyword, term_value in term_mappings.items():
            if keyword in question_lower:
                result['target_column'] = 'AETERM'
                result['filter_value'] = term_value
                return result

        result['reasoning'] = "Could not identify filter criteria"
        return result

#------------------------------------------------------------------------------
# Query Execution Function
#------------------------------------------------------------------------------

def query_exec(parsed_result, dataframe):
    """Execute query on ADAE dataframe and return results."""
    result = {
        "subject_count": 0,
        "subject_ids": [],
        "record_count": 0,
        "query_summary": ""
    }

    if not parsed_result['target_column'] or not parsed_result['filter_value']:
        result['query_summary'] = "Could not execute - no valid filter detected"
        return result

    target_col = parsed_result['target_column']
    filter_val = parsed_result['filter_value']

    # Apply Pandas filter
    filtered_df = dataframe[dataframe[target_col] == filter_val]
    unique_subjects = filtered_df['USUBJID'].unique().tolist()

    result['subject_count'] = len(unique_subjects)
    result['subject_ids'] = sorted(unique_subjects)
    result['record_count'] = len(filtered_df)
    result['query_summary'] = (
        f"✓ Found {result['subject_count']} unique subject(s) "
        f"with {result['record_count']} matching AE record(s)"
    )

    return result

#------------------------------------------------------------------------------
# Run 3 Test Queries
#------------------------------------------------------------------------------

# Initialize agent
agent = ClinicalTrialDataAgent(ADAE_SCHEMA)

# Three test queries
test_queries = [
    "Identify all subjects who experienced severe adverse events",
    "Which subjects had nervous system disorders?",
    "Show me all treatment-emergent adverse events"
]

print("="*80)
print("CLINICAL DATA ASSISTANT - TEST RESULTS")
print("="*80)

for i, question in enumerate(test_queries, 1):
    print(f"\n{'='*80}")
    print(f"TEST QUERY {i}")
    print('='*80)
    print(f"Question: {question}\n")

    # Parse the question
    parsed = agent.parse_question(question)
    print(f"Parsed Output:")
    print(f"  Target Column: {parsed['target_column']}")
    print(f"  Filter Value: {parsed['filter_value']}")

    # Execute the query
    results = query_exec(parsed, adae)
    print(f"Query Results:")
    print(f"  {results['query_summary']}\n")

    if results['subject_count'] > 0:
        print(f"  Complete List of Unique Subject IDs ({results['subject_count']} subjects):")
        for subj_id in results['subject_ids']:
            print(f"    - {subj_id}")

    print()

print("="*80)
print("✓ ALL TESTS COMPLETE")
print("="*80)